name: example
description: A new Flutter project.
# author: Yusril Rapsanjani<yuranicorp@gmail.com>
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.13.8'

dependencies:
  cupertino_icons: "any"
  flutter:
    sdk: flutter
  google_maps_flutter: any
  polymaker:
    path: ../

publish_to: 'none'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
